force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>Courses offered in SkillUp Application.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainee__c/Trainee__c.object-meta.xml
<CustomObject>
    <description>Trainees in SkillUp Application.</description>
    <label>Trainee</label>
    <nameField>
        <label>Trainee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainee</relationshipLabel>
    <relationshipName>Trainee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trainee__c/fields/Corporation__c.field-meta.xml
<CustomField>
    <fullName>Corporation__c</fullName>
    <label>Corporation</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trainee__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Trainee</relationshipLabel>
    <relationshipName>Trainee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/checkCRUDForLWC.cls
public class checkCRUDForLWC {
    @AuraEnabled
    public static Trainee__c createTraineeRecord(Id courseId, Id contactId){
        Trainee__c traineeObject = new Trainee__c();
        Contact conObject = [SELECT NAME, Email FROM Contact WHERE Id =: contactId];
        traineeObject.Course__c = courseId;
        traineeObject.Contact__c = contactId;
        traineeObject.Name = conObject.Name;
        //traineeObject.Corporation__c = conObject.AccountId;
        if(isCreateable('Trainee__c')==true){
            insert traineeObject;
            return traineeObject;
        }
        return null;
    }
    public static Boolean isCreateable(String sObjectType){
        SObjectType schemaType = Schema.getGlobalDescribe().get(sObjectType);
        return schemaType.getDescribe().isCreateable();
    }
}