force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>Courses offered in SkillUp Application.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trainee__c/Trainee__c.object-meta.xml
<CustomObject>
    <description>Trainees in SkillUp Application.</description>
    <label>Trainee</label>
    <nameField>
        <label>Trainee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainee__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Trainee</relationshipLabel>
    <relationshipName>Trainee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <description>Trainers of SkillUp Application.</description>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/certificateComponentController.cls
public class certificateComponentController 
{
    Public Trainee__c trainee {get;set;}
    Public Course__c course {get;set;}
    Public Trainer__c trainer {get;set;}
    
    public certificateComponentController() 
    {
        trainee=[SELECT Name, Course__c, Enrollment_Date__c FROM Trainee__c where Id=:ApexPages.currentPage().getParameters().get('id')];
        course=[Select Name, Trainer__c from Course__c Where id=:trainee.Course__c];
        trainer=[Select Name from Trainer__c where id=:course.Trainer__c];
    }
  }