force-app/main/default/objects/Account/fields/Last_Month_Dues__c.field-meta.xml
<CustomField>
    <fullName>Last_Month_Dues__c</fullName>
    <label>Last Month Dues</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trainee__c/Trainee__c.object-meta.xml
<CustomObject>
    <description>Trainees in SkillUp Application.</description>
    <label>Trainee</label>
    <nameField>
        <label>Trainee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainee__c/fields/Corporation__c.field-meta.xml
<CustomField>
    <fullName>Corporation__c</fullName>
    <label>Corporation</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountDue.cls
global class AccountDue implements Database.Batchable<sobject>
{
	List<AggregateResult> trainee_AggList = new List<AggregateResult>();
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        return Database.getQueryLocator([
            SELECT 
                Id,Last_Month_Dues__c,
                (SELECT Id, Name FROM Contacts WHERE Primary__c=true)
            FROM
                Account
            WHERE
                Id
            IN
                (SELECT AccountId FROM Contact WHERE Primary__c=true)]);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope) 
    {
        Set<Id> commonSet= new Set<Id>();
        for(Account acountobj : scope)
        {
                if(acountobj.Id !=null)
                  commonSet.add(acountobj.Id);
        }
        trainee_AggList = [Select Corporation__c,Sum(Course_fee__c) Total_Due 
                                                 from Trainee__c where Corporation__c in : commonSet
                                                 Group By Corporation__c ];
        List<Account> listofAccountsToUpdate = new List<Account>();
        for(Account acc : scope) {
            Map<String, Double> mapOfAccountsAndLastMonthDues = new Map<String, Double>();
			
            for(AggregateResult aggResult : trainee_AggList)
            {
                acc.Id = (String) aggResult.get('Corporation__c');
                acc.Last_Month_Dues__c = (Double) aggResult.get('Total_Due');
                listofAccountsToUpdate.add(acc);
            }
        }

        update listofAccountsToUpdate;
    }
    global void finish(Database.BatchableContext BC) 
    {
        List<Contact> listOfContacts = [SELECT Id, Name, Email, Account.Last_Month_Dues__c,Account.Name, AccountId FROM Contact 
                                        WHERE Primary__c=true];
        
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        
        for(Contact con : listOfContacts ) 
        {	
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			List<String> sendTo = new List<String>();
			sendTo.add(con.Email);
			mail.setToAddresses(sendTo);
			mail.setSenderDisplayName('Account Last Month Due');
			mail.setSubject('Last Month Due Of Account');
            String body = 'Dear' + con.Name + ',' + '<br>' +
                ' This is to inform you that your Account '+ con.Account.Name +' Last Month Due is ' + con.Account.Last_Month_Dues__c +'<br><br>'+ 
                'Thanks & Regards' + '<br><br>'+'Team SkillUp';
            mail.setHtmlBody(body);
            mails.add(mail);
    	}
        Messaging.sendEmail(mails);
	}
}